### ISSUE TITLE
Missing EN localization

### ISSUE THREAD

**Issue by Jack25apr** [diia-open-source/ios-diia#4]
Пропустимо, що хтось із закордону буде використовувати цей код - але локалізація лише Українська... було б круто мати EN-версію.

**Comment by DiiaOpenSource** [comment]
Привіт @Jack25apr 
Дякуємо за пропозицію. Насправді цей трек є у нас в планах. Однак зараз нема капасіті для того, щоб оперативно його реалізувати.

**Comment by valeriyvan** [comment]
Why the issue was closed? You have plans but don't have capacity. That's exact case where open source could be beneficial for the project. Why not to keep such issues leaving them for contributors? Reopen the issue and label it "help wanted".
