### ISSUE TITLE
Переписування проекту на SwiftUI

### ISSUE THREAD

**Issue by jaroshevskii** [diia-open-source/ios-diia#6]
Перехід на SwiftUI, дасть сучасний та простий у використанні підхід до створення інтерфейсів. Це також дозволить нам легко переносити код між різними платформами та прискорить розробку завдяки швидкому циклу та меншій кількості коду. Цей крок принесе нам більше можливостей та покращить продуктивність розробки.

1. **Створення Нових SwiftUI Views:** Почнемо зі створення нових SwiftUI Views, які будуть відповідальні за відображення основного інтерфейсу додатку.
2. **Інтеграція SwiftUI Views у Проект:** Після створення SwiftUI Views ми можемо інтегрувати їх у наш існуючий проект, замінюючи частини старого коду.
3. **Передача Даних між UIKit та SwiftUI:** Ми можемо використовувати UIViewRepresentable та UIViewControllerRepresentable для інтеграції SwiftUI Views у наші існуючі контролери.
3. **Поступова Заміна Коду:** Замінюйте частини старого коду SwiftUI-еквівалентами поступово, починаючи з найпростіших елементів та поступово переходячи до складніших.

**Comment by itrubik** [comment]
Ну вот пусть тебе chatgpt всё и перепишет

**Comment by maxoliinyk** [comment]
Поки що Дію анріал переписати на SwiftUI. Як мінімум через те, що потрібна максимальна підтримка пристроїв. Зараз мінімальна необхідна версія iOS 12, якщо переходити на SwiftUI, то ця версія буде швидко збільшуватись.

На ранніх етапах SwiftUI був занадто сирим фреймворком для апки такого рівня як Дія, тому треба накинути декілька версій, і на виході матимемо Дію, яку можна буде встановити лише з 15 або 16 iOS, що не є гарним результатом для додатка державного рівня.

З часом це зміниться, але я думаю ще декілька років не треба про це думати.
